# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29c334bc435264a279af9f48c275e3e1e59245c3c5d387c289029949bbb106d2603580c7efcbf356c129fbb1c356ddad51f830c867d1c1dfe195f4760decd315

test:
  secret_key_base: 75ed8cdf0cc0d4657b1838d865c87c02a73a56461f1d7ab486b4f74b12b8596723a361f2e147c1c5e664aaf084174265de944dd43c4a0730de90a7615838b716

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 29949bbb106d2603580c7efcbf356c129fbb1c356ddad51f830c867d1c1dfe195f4760decd31529c334bc435264a279af9f48c275e3e1e59245c3c5d387c2890
